const catchError = require('./catchError');
const handleInternalError = require('./handleInternalError');

module.exports = { catchError, handleInternalError };
